# Site settings
title:          Blog Hakim
description:    "Setiap orang punya cerita berbeda..."
url:            "https://hakim.orderio.my.id"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Nurul Hakim
  url:          https://hakim.orderio.my.id
  email:        hakim@orderio.my.id

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       7

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]
          - public/admin
          - node_modules

include:
  - _posts

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
